TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ID = "YOUR_CHAT_ID"

PO_EMAIL = "YOUR_POCKET_EMAIL"
PO_PASSWORD = "YOUR_POCKET_PASSWORD"

TRADE_AMOUNT = 1
TRADE_DURATION = 1   # minutes
CURRENCY = "EURUSD"  # trade pair
